## YAML Template.
---
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: e58a2cd0035fc8481541
            clientSecret: 7b361ccd6785ad836fe6ac3c67b7b3e666fd21ca

