## YAML Template.
---
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: f68f7bc642880bbfb659
            clientSecret: 3f133d4e7d0a750b29d9e8d6a78dfd8a48628fb8

